import { User, Listing, Conversation, SavedSearch, Review, Report, PlatformConfig } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-amina',
    email: 'amina.k@behalal-community.at',
    username: 'amina_vienna',
    firstName: 'Amina',
    lastName: 'Kovac',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    phone: '+43 660 1234567',
    country: 'Österreich',
    postalCode: '1100',
    city: 'Wien',
    language: 'de',
    role: 'USER',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2025-11-12T10:00:00Z',
    updatedAt: '2026-08-10T14:30:00Z',
    ratingAverage: 4.9,
    ratingCount: 19,
    responseRate: '100% (oft innerhalb weniger Minuten)',
    activeListingsCount: 3,
    blockedUserIds: [],
  },
  {
    id: 'user-bilal',
    email: 'bilal.m@behalal-community.at',
    username: 'bilal_graz',
    firstName: 'Bilal',
    lastName: 'Mujic',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    phone: '+43 676 9876543',
    country: 'Österreich',
    postalCode: '8020',
    city: 'Graz',
    language: 'bs',
    role: 'USER',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2025-12-05T08:15:00Z',
    updatedAt: '2026-08-15T09:20:00Z',
    ratingAverage: 5.0,
    ratingCount: 14,
    responseRate: '95%',
    activeListingsCount: 2,
    blockedUserIds: [],
  },
  {
    id: 'user-fatima',
    email: 'fatima.s@behalal-community.at',
    username: 'fatima_linz',
    firstName: 'Fatima',
    lastName: 'Saric',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    country: 'Österreich',
    postalCode: '4020',
    city: 'Linz',
    language: 'de',
    role: 'USER',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2026-01-10T16:00:00Z',
    updatedAt: '2026-08-18T11:00:00Z',
    ratingAverage: 4.8,
    ratingCount: 8,
    responseRate: '98%',
    activeListingsCount: 2,
    blockedUserIds: [],
  },
  {
    id: 'user-mod-tariq',
    email: 'tariq.mod@behalal-community.at',
    username: 'tariq_moderator',
    firstName: 'Tariq',
    lastName: 'Halilovic',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    country: 'Österreich',
    postalCode: '5020',
    city: 'Salzburg',
    language: 'de',
    role: 'MODERATOR',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2025-10-01T09:00:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
    ratingAverage: 5.0,
    ratingCount: 32,
    responseRate: '100%',
    activeListingsCount: 1,
    blockedUserIds: [],
  },
  {
    id: 'user-admin',
    email: 'admin@behalal-bazar.at',
    username: 'admin_behalal',
    firstName: 'Admin',
    lastName: 'ONLINE BAZAR',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    country: 'Österreich',
    postalCode: '1010',
    city: 'Wien',
    language: 'de',
    role: 'ADMIN',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-08-21T10:00:00Z',
    ratingAverage: 5.0,
    ratingCount: 50,
    responseRate: '100%',
    activeListingsCount: 1,
    blockedUserIds: [],
  },
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'lst-1',
    userId: 'user-amina',
    type: 'SELL',
    title: 'Woom 3 Kinderfahrrad 16 Zoll – Rot – Sehr gepflegt',
    description: 'Wir verkaufen das geliebte Woom 3 unseres Sohnes in der Farbe Rot (16 Zoll). Sehr leichtes Aluminiumrad, ideal zum Fahrradfahren lernen. Wurde immer im trockenen Keller abgestellt. Inklusive Original Woom Seitenständer und Klingel. Bereifung in Top-Zustand.',
    categoryId: 'sports-leisure',
    subcategoryId: 'bikes',
    brand: 'Woom',
    condition: 'VERY_GOOD',
    price: 340,
    negotiable: true,
    isFree: false,
    deliveryType: 'BOTH',
    country: 'Österreich',
    postalCode: '1100',
    city: 'Wien',
    status: 'ACTIVE',
    views: 142,
    favoritesCount: 16,
    images: [
      { id: 'img-1-1', url: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
      { id: 'img-1-2', url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=900&auto=format&fit=crop&q=80', sortOrder: 1, isCover: false },
      { id: 'img-1-3', url: 'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=900&auto=format&fit=crop&q=80', sortOrder: 2, isCover: false },
    ],
    createdAt: '2026-08-19T14:20:00Z',
    updatedAt: '2026-08-19T14:20:00Z',
    publishedAt: '2026-08-19T14:20:00Z',
    expiresAt: '2026-10-19T14:20:00Z',
    seller: {
      id: 'user-amina',
      username: 'amina_vienna',
      firstName: 'Amina',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 4.9,
      ratingCount: 19,
      memberSince: 'Nov. 2025',
      emailVerified: true,
      city: 'Wien',
      postalCode: '1100',
    },
  },
  {
    id: 'lst-2',
    userId: 'user-bilal',
    type: 'SELL',
    title: 'Cybex Priam Kombi-Kinderwagen Komplettset (Wanne + Sportsitz)',
    description: 'Verkaufen unseren Cybex Priam Kinderwagen in edlem Matt-Schwarz mit Roségold Gestell. Enthält die Babywanne (Lux Carry Cot) sowie den bequemen Sportsitz. Regenschutz und Adapter für Babyschale sind dabei. Tierfreier Nichtraucherhaushalt, keine Flecken.',
    categoryId: 'baby-kids',
    subcategoryId: 'strollers',
    brand: 'Cybex',
    condition: 'LIKE_NEW',
    price: 680,
    negotiable: true,
    isFree: false,
    deliveryType: 'PICKUP',
    country: 'Österreich',
    postalCode: '8020',
    city: 'Graz',
    status: 'ACTIVE',
    views: 215,
    favoritesCount: 24,
    images: [
      { id: 'img-2-1', url: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
      { id: 'img-2-2', url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=900&auto=format&fit=crop&q=80', sortOrder: 1, isCover: false },
    ],
    createdAt: '2026-08-18T09:40:00Z',
    updatedAt: '2026-08-18T09:40:00Z',
    publishedAt: '2026-08-18T09:40:00Z',
    expiresAt: '2026-10-18T09:40:00Z',
    seller: {
      id: 'user-bilal',
      username: 'bilal_graz',
      firstName: 'Bilal',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 5.0,
      ratingCount: 14,
      memberSince: 'Dez. 2025',
      emailVerified: true,
      city: 'Graz',
      postalCode: '8020',
    },
  },
  {
    id: 'lst-3',
    userId: 'user-fatima',
    type: 'SELL',
    title: 'Apple iPhone 15 Pro – 256GB Titan Natur – Wie neu mit OVP & Rechnung',
    description: 'Biete mein iPhone 15 Pro mit 256 GB Speicher in Titan Natur an. Akkukapazität liegt bei 98%. Wurde vom ersten Tag an mit Panzerglas und originaler Hülle genutzt, daher absolut kratzerfrei. Mit Originalverpackung, USB-C Ladekabel und Rechnung.',
    categoryId: 'electronics',
    subcategoryId: 'smartphones',
    brand: 'Apple',
    condition: 'LIKE_NEW',
    price: 890,
    negotiable: false,
    isFree: false,
    deliveryType: 'BOTH',
    country: 'Österreich',
    postalCode: '4020',
    city: 'Linz',
    status: 'ACTIVE',
    views: 310,
    favoritesCount: 35,
    images: [
      { id: 'img-3-1', url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
      { id: 'img-3-2', url: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=900&auto=format&fit=crop&q=80', sortOrder: 1, isCover: false },
    ],
    createdAt: '2026-08-20T11:15:00Z',
    updatedAt: '2026-08-20T11:15:00Z',
    publishedAt: '2026-08-20T11:15:00Z',
    expiresAt: '2026-10-20T11:15:00Z',
    seller: {
      id: 'user-fatima',
      username: 'fatima_linz',
      firstName: 'Fatima',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 4.8,
      ratingCount: 8,
      memberSince: 'Jän. 2026',
      emailVerified: true,
      city: 'Linz',
      postalCode: '4020',
    },
  },
  {
    id: 'lst-4',
    userId: 'user-amina',
    type: 'FREE',
    title: 'Großes Paket Babykleidung Gr. 62/68 für Jungen (Bodys, Strampler, Mützen)',
    description: 'Verschenke eine Kiste gut erhaltener Babykleidung an eine Familie in unserer Community. Alles frisch gewaschen, aus reiner Bio-Baumwolle. Enthält ca. 20 Teile (Langarm-Bodys, Hosen, Schlafanzüge). Nur zur Selbstabholung in Wien 10.',
    categoryId: 'baby-kids',
    subcategoryId: 'baby-clothes',
    brand: 'H&M / C&A / Alana',
    condition: 'GOOD',
    price: 0,
    negotiable: false,
    isFree: true,
    deliveryType: 'PICKUP',
    country: 'Österreich',
    postalCode: '1100',
    city: 'Wien',
    status: 'ACTIVE',
    views: 180,
    favoritesCount: 22,
    images: [
      { id: 'img-4-1', url: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
    ],
    createdAt: '2026-08-21T08:00:00Z',
    updatedAt: '2026-08-21T08:00:00Z',
    publishedAt: '2026-08-21T08:00:00Z',
    expiresAt: '2026-10-21T08:00:00Z',
    seller: {
      id: 'user-amina',
      username: 'amina_vienna',
      firstName: 'Amina',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 4.9,
      ratingCount: 19,
      memberSince: 'Nov. 2025',
      emailVerified: true,
      city: 'Wien',
      postalCode: '1100',
    },
  },
  {
    id: 'lst-5',
    userId: 'user-bilal',
    type: 'WANTED',
    title: 'SUCHE: Esstisch Massivholz Eiche ausziehbar (mind. 160–220 cm)',
    description: 'Salam aleikum Geschwister, wir suchen für unser neues Esszimmer einen stabilen Echtholz-Esstisch (vorzugsweise Eiche oder Buche), der sich ausziehen lässt. Gerne in Graz und Umgebung bis 30 km Umkreis. Budget ca. 300–450 € je nach Zustand.',
    categoryId: 'furniture-living',
    subcategoryId: 'tables-chairs',
    condition: 'VERY_GOOD',
    price: 450,
    maxBudget: 450,
    negotiable: true,
    isFree: false,
    deliveryType: 'PICKUP',
    country: 'Österreich',
    postalCode: '8020',
    city: 'Graz',
    status: 'ACTIVE',
    views: 95,
    favoritesCount: 7,
    images: [
      { id: 'img-5-1', url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
    ],
    createdAt: '2026-08-20T16:30:00Z',
    updatedAt: '2026-08-20T16:30:00Z',
    publishedAt: '2026-08-20T16:30:00Z',
    expiresAt: '2026-10-20T16:30:00Z',
    seller: {
      id: 'user-bilal',
      username: 'bilal_graz',
      firstName: 'Bilal',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 5.0,
      ratingCount: 14,
      memberSince: 'Dez. 2025',
      emailVerified: true,
      city: 'Graz',
      postalCode: '8020',
    },
  },
  {
    id: 'lst-6',
    userId: 'user-mod-tariq',
    type: 'SELL',
    title: 'Bosch Professional Akku-Bohrschrauber GSR 12V-15 Set mit 2x Akkus & Lader',
    description: 'Verkaufe handlichen und kraftvollen Bosch Blau Akkuschrauber. Perfekt für den Möbelaufbau und Haushaltsarbeiten. Inklusive 2 Stück 2.0 Ah Li-Ion Akkus, Schnellladegerät und praktischer Tasche. Wurde nur für einen Umzug genutzt.',
    categoryId: 'garden-tools',
    subcategoryId: 'power-tools',
    brand: 'Bosch Professional',
    condition: 'LIKE_NEW',
    price: 95,
    negotiable: false,
    isFree: false,
    deliveryType: 'BOTH',
    country: 'Österreich',
    postalCode: '5020',
    city: 'Salzburg',
    status: 'ACTIVE',
    views: 120,
    favoritesCount: 11,
    images: [
      { id: 'img-6-1', url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
    ],
    createdAt: '2026-08-17T18:00:00Z',
    updatedAt: '2026-08-17T18:00:00Z',
    publishedAt: '2026-08-17T18:00:00Z',
    expiresAt: '2026-10-17T18:00:00Z',
    seller: {
      id: 'user-mod-tariq',
      username: 'tariq_moderator',
      firstName: 'Tariq',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 5.0,
      ratingCount: 32,
      memberSince: 'Okt. 2025',
      emailVerified: true,
      city: 'Salzburg',
      postalCode: '5020',
    },
  },
  {
    id: 'lst-7',
    userId: 'user-fatima',
    type: 'SELL',
    title: 'Sammlung islamische Kinderbücher & Propheten-Geschichten (7 Bände, Hardcover)',
    description: 'Schöne, liebevoll illustrierte Kinderbuch-Reihe mit Propheten-Geschichten und Grundlagen des Islam in deutscher Sprache. Sehr verständlich für Kinder von 4–10 Jahren. Bücher sind in neuwertigem Zustand ohne Knicke oder Risse.',
    categoryId: 'books-media',
    subcategoryId: 'islamic-books',
    condition: 'LIKE_NEW',
    price: 45,
    negotiable: true,
    isFree: false,
    deliveryType: 'BOTH',
    country: 'Österreich',
    postalCode: '4020',
    city: 'Linz',
    status: 'ACTIVE',
    views: 160,
    favoritesCount: 19,
    images: [
      { id: 'img-7-1', url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
      { id: 'img-7-2', url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=900&auto=format&fit=crop&q=80', sortOrder: 1, isCover: false },
    ],
    createdAt: '2026-08-16T12:00:00Z',
    updatedAt: '2026-08-16T12:00:00Z',
    publishedAt: '2026-08-16T12:00:00Z',
    expiresAt: '2026-10-16T12:00:00Z',
    seller: {
      id: 'user-fatima',
      username: 'fatima_linz',
      firstName: 'Fatima',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 4.8,
      ratingCount: 8,
      memberSince: 'Jän. 2026',
      emailVerified: true,
      city: 'Linz',
      postalCode: '4020',
    },
  },
  {
    id: 'lst-8',
    userId: 'user-admin',
    type: 'SELL',
    title: 'DeLonghi Magnifica S Kaffeevollautomat – Frisch entkalkt & gewartet',
    description: 'Zuverlässiger Kaffeevollautomat mit Milchschaumdüse. Mahlgrad stufenlos einstellbar. Maschine wurde regelmäßig gewartet, die Brühgruppe gereinigt und frisch mit Original-Entkalker entkalkt. Funktioniert einwandfrei.',
    categoryId: 'household',
    subcategoryId: 'kitchen',
    brand: 'DeLonghi',
    condition: 'VERY_GOOD',
    price: 160,
    negotiable: true,
    isFree: false,
    deliveryType: 'BOTH',
    country: 'Österreich',
    postalCode: '1010',
    city: 'Wien',
    status: 'ACTIVE',
    views: 198,
    favoritesCount: 14,
    images: [
      { id: 'img-8-1', url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=900&auto=format&fit=crop&q=80', sortOrder: 0, isCover: true },
    ],
    createdAt: '2026-08-15T15:10:00Z',
    updatedAt: '2026-08-15T15:10:00Z',
    publishedAt: '2026-08-15T15:10:00Z',
    expiresAt: '2026-10-15T15:10:00Z',
    seller: {
      id: 'user-admin',
      username: 'admin_behalal',
      firstName: 'Admin',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
      ratingAverage: 5.0,
      ratingCount: 50,
      memberSince: 'Sep. 2025',
      emailVerified: true,
      city: 'Wien',
      postalCode: '1010',
    },
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    listingId: 'lst-1',
    listingTitle: 'Woom 3 Kinderfahrrad 16 Zoll – Rot',
    listingPrice: 340,
    listingType: 'SELL',
    listingImage: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=300&auto=format&fit=crop&q=80',
    listingStatus: 'ACTIVE',
    buyerId: 'user-bilal',
    buyerName: 'Bilal Mujic',
    buyerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    sellerId: 'user-amina',
    sellerName: 'Amina Kovac',
    sellerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    lastMessage: 'Perfekt, dann bis morgen um 17:00 Uhr in Wien 10! Vielen Dank.',
    lastMessageAt: '2026-08-21T11:45:00Z',
    unreadCountForUser: 0,
  },
  {
    id: 'conv-2',
    listingId: 'lst-3',
    listingTitle: 'Apple iPhone 15 Pro – 256GB Titan Natur',
    listingPrice: 890,
    listingType: 'SELL',
    listingImage: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=300&auto=format&fit=crop&q=80',
    listingStatus: 'ACTIVE',
    buyerId: 'user-amina',
    buyerName: 'Amina Kovac',
    buyerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    sellerId: 'user-fatima',
    sellerName: 'Fatima Saric',
    sellerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    lastMessage: 'Salam Fatima! Ist das Handy noch verfügbar und wäre versicherter Versand möglich?',
    lastMessageAt: '2026-08-21T13:20:00Z',
    unreadCountForUser: 1,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    reviewerId: 'user-bilal',
    reviewerName: 'Bilal M.',
    reviewerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    reviewedUserId: 'user-amina',
    rating: 5,
    tags: ['Sehr freundlich', 'Sehr zuverlässig', 'Artikel genau wie beschrieben'],
    comment: 'Sehr herzliche und unkomplizierte Übergabe. Das Fahrrad war genau im beschriebenen Top-Zustand!',
    createdAt: '2026-07-15T16:00:00Z',
  },
  {
    id: 'rev-2',
    reviewerId: 'user-fatima',
    reviewerName: 'Fatima S.',
    reviewerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    reviewedUserId: 'user-amina',
    rating: 5,
    tags: ['Schnelle Antwort', 'Unkomplizierte Abwicklung'],
    comment: 'Alles bestens, gerne wieder.',
    createdAt: '2026-06-20T10:30:00Z',
  },
];

export const INITIAL_SAVED_SEARCHES: SavedSearch[] = [
  {
    id: 'search-1',
    userId: 'user-amina',
    title: 'Kinderfahrrad Wien bis 350 €',
    query: 'Kinderfahrrad',
    categoryId: 'sports-leisure',
    maxPrice: 350,
    city: 'Wien',
    radiusKm: 25,
    notificationFrequency: 'INSTANT',
    createdAt: '2026-08-01T10:00:00Z',
    matchCount: 4,
  },
  {
    id: 'search-2',
    userId: 'user-bilal',
    title: 'Islamische Kinderbücher',
    query: 'Bücher',
    categoryId: 'books-media',
    notificationFrequency: 'DAILY',
    createdAt: '2026-08-10T12:00:00Z',
    matchCount: 2,
  },
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep-1',
    reporterId: 'user-fatima',
    reporterName: 'Fatima S.',
    listingId: 'lst-99-demo',
    listingTitle: 'Verkaufe Reinigungsdienst für Wohnungen',
    reason: 'SERVICE_JOB',
    description: 'Dienstleistungen sind laut den Community-Regeln der ONLINE BAZAR Gruppe nicht gestattet.',
    status: 'RESOLVED',
    moderatorNotes: 'Inserat gelöscht und Nutzer verwarnt.',
    moderatorId: 'user-mod-tariq',
    createdAt: '2026-08-18T14:00:00Z',
    resolvedAt: '2026-08-18T14:20:00Z',
  },
];

export const INITIAL_CONFIG: PlatformConfig = {
  maxListingsPerDay: 2,
  repostCooldownDays: 14,
  maxPhotosPerListing: 8,
  listingExpiryDays: 60,
  autoModerationActive: true,
  registrationOpen: true,
  emailVerificationRequired: true,
  bannedKeywords: [
    'job', 'jobangebot', 'arbeit gesucht', 'stelle frei',
    'wohnung mieten', 'wohnung vermieten', 'immobilie', 'nachmieter', 'wg-zimmer',
    'katze', 'hund', 'welpe', 'vogel', 'tierverkauf', 'kätzchen',
    'dienstleistung', 'reinigungsservice', 'handwerker service',
    'waffe', 'pistole', 'messer', 'drogen', 'shisha tabak', 'vape',
    'fake', 'replica', 'replik', '1:1 kopie', 'plagiat', 'nachbau'
  ],
};
